package com.example.onboarding.enums;

public enum CandidateRole {
	DEVELOPER, TESTER, ANALYST, DESIGNER, DEVOPS_ENGINEER, PROJECT_MANAGER, PRODUCT_OWNER, SCRUM_MASTER, QA_ENGINEER,
	DATA_SCIENTIST, BUSINESS_ANALYST, SYSTEM_ADMINISTRATOR, UI_UX_DESIGNER
}
