package com.example.onboarding.enums;

public enum OnboardStatus {
	DOCUMENT_PENDING, DOCUMENT_VERIFIED, BACKGROUND_CHECK_PENDING, BACKGROUND_CHECK_COMPLETED, ORIENTATION_SCHEDULED,
	OFFER_ACCEPTED, IT_SETUP_IN_PROGRESS, IN_PROGRESS, COMPLETED, TERMINATED
}
